version: '3'

networks:
  default:
    driver: bridge

services:

  redis:
    image: redis:alpine
    expose:
      - "6379"

  mariadb:
    build: ./docker/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123asd
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=qwe123asd
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - default

  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/sites/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_OPCACHE=true
        - INSTALL_PHPREDIS=true
    volumes:
      - ./:/var/www:cached
    command: sh -c 'composer install; /wait-for-it.sh mariadb:3306 -t 60; php artisan migrate; php-fpm;'
    expose:
      - "9000"
    networks:
      - default

  php-cli:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_XDEBUG=true
    volumes:
      - ./:/var/www:cached
    working_dir: /var/www
    networks:
      - default

  horizon:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_REDIS=true
    volumes:
      - ./:/var/www:cached
    working_dir: /var/www
    command: sh -c '/wait-for-it.sh redis:6379 -t 60; php artisan horizon'
    depends_on:
      - redis
      - mariadb
    networks:
      - default

  node:
    image: node:8
    volumes:
      - ./:/var/www
    command: sh -c 'npm install; npm run watch'
    working_dir: /var/www
    networks:
      - default